# Generated by Django 5.0.7 on 2024-09-03 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('houseno', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('housedescription', models.CharField(max_length=100)),
                ('pernight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('clientname', models.CharField(max_length=100)),
                ('contactdetails', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('houseno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestay.apartment')),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestay.client')),
            ],
        ),
    ]
