# Generated by Django 5.0.7 on 2024-09-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
