# Generated by Django 5.0.7 on 2024-09-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('programmmecode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('programmename', models.CharField(max_length=100)),
                ('programmeaccdate', models.DateField()),
            ],
        ),
    ]
