# Generated by Django 5.0.7 on 2024-09-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentorid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mentorname', models.CharField(max_length=100)),
                ('mentoremail', models.CharField(max_length=100)),
            ],
        ),
    ]
