# Generated by Django 5.0.7 on 2024-09-26 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('studentname', models.CharField(max_length=100)),
                ('mentorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.mentor')),
            ],
        ),
    ]
