# Generated by Django 5.0.7 on 2024-08-21 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custic', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('custname', models.CharField(max_length=60)),
                ('custphone', models.IntegerField(null=True)),
                ('custemail', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('platno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=60)),
                ('capacity', models.IntegerField(null=True)),
                ('datepurchased', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
                ('totalcost', models.IntegerField(null=True)),
                ('custic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycompany.customer')),
                ('platno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycompany.vehicle')),
            ],
        ),
    ]
