# Generated by Django 5.0.7 on 2024-10-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentorid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mentorname', models.CharField(max_length=100)),
                ('mentorcourse', models.CharField(max_length=5)),
                ('mentorphonenum', models.CharField(max_length=20)),
                ('mentoremail', models.CharField(max_length=50)),
                ('mentorpassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectcode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subjectname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('studentname', models.CharField(max_length=100)),
                ('studentcourse', models.CharField(max_length=5)),
                ('studentphonenum', models.CharField(max_length=20)),
                ('studentemail', models.CharField(max_length=100)),
                ('studentpassword', models.CharField(max_length=20)),
                ('studentmentorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myeduclinic.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('tuitioncode', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('tuitionmeet', models.TextField(max_length=200)),
                ('tuitiondate', models.DateField()),
                ('tuitionduration', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('subjectcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myeduclinic.subject')),
                ('tuitionmentorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myeduclinic.mentor')),
                ('tuitionstudentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myeduclinic.student')),
            ],
        ),
    ]
