# Generated by Django 5.0.7 on 2024-10-12 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeduclinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mentorcourse',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentoremail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentorname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentorpassword',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentorphonenum',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentcourse',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentemail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentmentorid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myeduclinic.mentor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentpassword',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentphonenum',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='tuitiondate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='tuitionduration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='tuitionmeet',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
