# Generated by Django 5.0.7 on 2024-08-27 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('singerid', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('singername', models.CharField(max_length=100)),
                ('singerorigin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumname', models.CharField(max_length=100)),
                ('albumyear', models.IntegerField()),
                ('singerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songlist.singer')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('songid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('songname', models.CharField(max_length=100)),
                ('minutes', models.IntegerField()),
                ('albumid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songlist.album')),
            ],
        ),
    ]
