# Generated by Django 5.0.7 on 2024-09-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrolment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
